# Generated by Django 5.0.6 on 2026-06-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='storage_path',
        ),
    ]
