# Generated by Django 6.0.5 on 2026-06-02 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя')),
                ('unique_name', models.CharField(max_length=500, unique=True, verbose_name='Уникальное имя')),
                ('size', models.BigIntegerField(verbose_name='Размер в байтах')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('last_download_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('share_link', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Специальная ссылка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'files',
            },
        ),
    ]
